# permissions for end users to view releasestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releasestore-viewer-role
rules:
- apiGroups:
  - release-controller.io
  resources:
  - releasestores
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - release-controller.io
  resources:
  - releasestores/status
  verbs:
  - get
