# permissions for end users to edit releasestores.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: releasestore-editor-role
rules:
- apiGroups:
  - release-controller.io.release-controller.io
  resources:
  - releasestores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - release-controller.io.release-controller.io
  resources:
  - releasestores/status
  verbs:
  - get
